services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11400:11400"
    volumes:
      - ollama_data:/root/.ollama
    command: ["ollama", "pull", "zephyr:7b"]

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "4000:4000"
    depends_on:
      - ollama
    environment:
      OLLAMA_SERVER_URL: http://ollama:11400

volumes:
  ollama_data:  