services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    hostname: openwebui
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    environment:
      OLLAMA_SERVER_URL: http://ollama:11434

volumes:
  ollama_data:  